on:
  pull_request: {}
  push:
    branches:
    - master
    paths:
    - .github/workflows/semgrep.yml
name: Semgrep
jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: returntocorp/semgrep-action@v1
      with:
        config: >- # more at semgrep.dev/explore
            p/security-audit
            p/secrets
        publishToken: ${{ secrets.SEMGREP_APP_TOKEN }}
